import type { ParsedDecision } from "./parse";

/**
 * Demo cases so the UI is fully usable BEFORE any real ingestion. These are
 * synthetic — every demo row carries confidence._demo = 1 so the UI can show a
 * "Demo" chip and never mistake fake data for a real Mahkamah Agung decision.
 * Source URLs point at the real public site so provenance links stay valid.
 */

export type DemoCase = ParsedDecision & { sourceUrl: string };

const SRC = "https://putusan3.mahkamahagung.go.id/direktori/putusan";

function demo(p: Partial<ParsedDecision> & { sourceUrl: string }): DemoCase {
  return {
    nomorPutusan: null,
    tingkatProses: null,
    klasifikasi: null,
    kataKunci: [],
    tahun: null,
    tanggalRegister: null,
    tanggalPutusan: null,
    tanggalMusyawarah: null,
    lembagaPeradilan: null,
    jenisLembagaPeradilan: null,
    pengadilan: null,
    provinsi: null,
    hakim: [],
    panitera: null,
    pihak: [],
    pemohon: null,
    termohon: null,
    terdakwa: null,
    penggugat: null,
    tergugat: null,
    amarPutusan: null,
    ringkasanSingkat: null,
    fullText: null,
    pdfUrl: null,
    extractionStatus: "complete",
    ...p,
    confidence: { _demo: 1, ...(p.confidence ?? {}) },
  } as DemoCase;
}

export const DEMO_CASES: DemoCase[] = [
  demo({
    sourceUrl: `${SRC}/demo-2451kpidsus2021`,
    nomorPutusan: "2451 K/Pid.Sus/2021",
    tingkatProses: "Kasasi",
    klasifikasi: "Pidana Khusus",
    kataKunci: ["tindak pidana korupsi", "kerugian negara", "kasasi"],
    tahun: 2021,
    tanggalRegister: "2021-05-12",
    tanggalMusyawarah: "2021-09-28",
    tanggalPutusan: "2021-09-28",
    lembagaPeradilan: "Mahkamah Agung",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "Mahkamah Agung",
    provinsi: "DKI Jakarta",
    hakim: ["Dr. Suhadi, S.H., M.H.", "Sri Murwahyuni, S.H., M.H.", "Sofyan Sitompul, S.H., M.H."],
    panitera: "H. Maruli, S.H.",
    terdakwa: "AS bin SR",
    pihak: ["Jaksa Penuntut Umum", "AS bin SR"],
    amarPutusan:
      "Menolak permohonan kasasi dari Pemohon Kasasi/Terdakwa; Membebankan biaya perkara kepada Terdakwa sebesar Rp2.500,00.",
    ringkasanSingkat:
      "Kasasi terhadap putusan tindak pidana korupsi ditolak; putusan judex facti dikuatkan.",
    fullText:
      "P U T U S A N\nNomor 2451 K/Pid.Sus/2021\nDEMI KEADILAN BERDASARKAN KETUHANAN YANG MAHA ESA\nMahkamah Agung memeriksa perkara pidana khusus pada tingkat kasasi telah memutus sebagai berikut.\n\nMENIMBANG bahwa alasan-alasan kasasi tidak dapat dibenarkan karena judex facti tidak salah menerapkan hukum.\n\nMENGADILI\nMenolak permohonan kasasi dari Pemohon Kasasi/Terdakwa AS bin SR tersebut; Membebankan biaya perkara dalam tingkat kasasi kepada Terdakwa sebesar Rp2.500,00.\n\nDemikian diputuskan dalam rapat permusyawaratan Majelis Hakim.",
    pdfUrl: `${SRC}/demo-2451kpidsus2021/pdf`,
  }),
  demo({
    sourceUrl: `${SRC}/demo-118pkpdt2020`,
    nomorPutusan: "118 PK/Pdt/2020",
    tingkatProses: "Peninjauan Kembali",
    klasifikasi: "Perdata",
    kataKunci: ["wanprestasi", "perjanjian jual beli", "peninjauan kembali"],
    tahun: 2020,
    tanggalRegister: "2020-02-03",
    tanggalPutusan: "2020-07-15",
    lembagaPeradilan: "Mahkamah Agung",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "Mahkamah Agung",
    provinsi: "Jawa Barat",
    hakim: ["I Gusti Agung Sumanatha, S.H., M.H.", "Nurul Elmiyah, S.H., M.H."],
    panitera: "Rahmi Mulyati, S.H., M.H.",
    penggugat: "PT Sumber Makmur",
    tergugat: "CV Cahaya Abadi",
    pihak: ["PT Sumber Makmur", "CV Cahaya Abadi"],
    amarPutusan:
      "Menolak permohonan peninjauan kembali dari Pemohon Peninjauan Kembali; Menghukum Pemohon membayar biaya perkara.",
    ringkasanSingkat: "PK atas sengketa wanprestasi perjanjian jual beli ditolak.",
    fullText:
      "P U T U S A N\nNomor 118 PK/Pdt/2020\nMENIMBANG bahwa tidak terdapat kekhilafan hakim atau kekeliruan yang nyata.\nMENGADILI\nMenolak permohonan peninjauan kembali dari Pemohon Peninjauan Kembali PT Sumber Makmur tersebut.",
    pdfUrl: `${SRC}/demo-118pkpdt2020/pdf`,
  }),
  demo({
    sourceUrl: `${SRC}/demo-87pidb2022pnsby`,
    nomorPutusan: "87/Pid.B/2022/PN Sby",
    tingkatProses: "Pertama",
    klasifikasi: "Pidana Umum",
    kataKunci: ["penipuan", "pasal 378 KUHP"],
    tahun: 2022,
    tanggalRegister: "2022-01-20",
    tanggalPutusan: "2022-04-11",
    lembagaPeradilan: "Pengadilan Negeri Surabaya",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "PN Surabaya",
    provinsi: "Jawa Timur",
    hakim: ["Bambang Setiawan, S.H.", "Dewi Anggraini, S.H., M.H."],
    panitera: "Sutrisno, S.H.",
    terdakwa: "BD alias Budi",
    pihak: ["Jaksa Penuntut Umum", "BD alias Budi"],
    amarPutusan:
      "Menyatakan Terdakwa terbukti secara sah dan meyakinkan bersalah melakukan tindak pidana penipuan; Menjatuhkan pidana penjara selama 1 (satu) tahun 6 (enam) bulan.",
    ringkasanSingkat: "Terdakwa dinyatakan bersalah atas penipuan dan dipidana 1 tahun 6 bulan.",
    fullText:
      "P U T U S A N\nNomor 87/Pid.B/2022/PN Sby\nMENGADILI\n1. Menyatakan Terdakwa BD alias Budi terbukti secara sah dan meyakinkan bersalah melakukan tindak pidana penipuan;\n2. Menjatuhkan pidana kepada Terdakwa dengan pidana penjara selama 1 tahun dan 6 bulan;\n3. Menetapkan masa penangkapan dan penahanan dikurangkan seluruhnya dari pidana yang dijatuhkan.",
    pdfUrl: null,
  }),
  demo({
    sourceUrl: `${SRC}/demo-340pdtg2021pnjktpst`,
    nomorPutusan: "340/Pdt.G/2021/PN Jkt.Pst",
    tingkatProses: "Pertama",
    klasifikasi: "Perdata",
    kataKunci: ["perbuatan melawan hukum", "ganti rugi"],
    tahun: 2021,
    tanggalPutusan: "2021-11-02",
    lembagaPeradilan: "Pengadilan Negeri Jakarta Pusat",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "PN Jakarta Pusat",
    provinsi: "DKI Jakarta",
    hakim: ["Hariyanto, S.H., M.H."],
    penggugat: "Yayasan Lestari",
    tergugat: "PT Bangun Sejahtera",
    pihak: ["Yayasan Lestari", "PT Bangun Sejahtera"],
    amarPutusan:
      "Mengabulkan gugatan Penggugat untuk sebagian; Menyatakan Tergugat telah melakukan perbuatan melawan hukum; Menghukum Tergugat membayar ganti rugi.",
    ringkasanSingkat: "Gugatan PMH dikabulkan sebagian; Tergugat dihukum membayar ganti rugi.",
    fullText:
      "P U T U S A N\nNomor 340/Pdt.G/2021/PN Jkt.Pst\nMENGADILI\nMengabulkan gugatan Penggugat untuk sebagian; Menyatakan Tergugat melakukan perbuatan melawan hukum; Menghukum Tergugat untuk membayar ganti kerugian.",
    pdfUrl: `${SRC}/demo-340pdtg2021pnjktpst/pdf`,
  }),
  demo({
    sourceUrl: `${SRC}/demo-15ptun2023`,
    nomorPutusan: "15/G/2023/PTUN.Mdn",
    tingkatProses: "Pertama",
    klasifikasi: "Tata Usaha Negara",
    kataKunci: ["sengketa tata usaha negara", "izin", "keputusan pejabat"],
    tahun: 2023,
    tanggalPutusan: "2023-06-19",
    lembagaPeradilan: "Pengadilan Tata Usaha Negara Medan",
    jenisLembagaPeradilan: "Tata Usaha Negara",
    pengadilan: "PTUN Medan",
    provinsi: "Sumatera Utara",
    hakim: ["Saut Maruli, S.H., M.H.", "Lina Marlina, S.H."],
    penggugat: "PT Agro Nusantara",
    tergugat: "Kepala Dinas Penanaman Modal",
    pihak: ["PT Agro Nusantara", "Kepala Dinas Penanaman Modal"],
    amarPutusan:
      "Mengabulkan gugatan Penggugat; Menyatakan batal Keputusan Tergugat; Mewajibkan Tergugat mencabut keputusan objek sengketa.",
    ringkasanSingkat: "Gugatan TUN dikabulkan; keputusan pejabat dinyatakan batal.",
    fullText:
      "P U T U S A N\nNomor 15/G/2023/PTUN.Mdn\nMENGADILI\nMengabulkan gugatan Penggugat untuk seluruhnya; Menyatakan batal Keputusan Tata Usaha Negara objek sengketa; Mewajibkan Tergugat untuk mencabutnya.",
    pdfUrl: `${SRC}/demo-15ptun2023/pdf`,
  }),
  demo({
    sourceUrl: `${SRC}/demo-902kpdt2019`,
    nomorPutusan: "902 K/Pdt/2019",
    tingkatProses: "Kasasi",
    klasifikasi: "Perdata",
    kataKunci: ["sengketa tanah", "sertifikat hak milik"],
    tahun: 2019,
    tanggalPutusan: "2019-08-21",
    lembagaPeradilan: "Mahkamah Agung",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "Mahkamah Agung",
    provinsi: "Bali",
    hakim: ["Soltoni Mohdally, S.H., M.H.", "Hamdi, S.H., M.Hum."],
    pihak: ["I Made Sukerta", "I Nyoman Gede"],
    penggugat: "I Made Sukerta",
    tergugat: "I Nyoman Gede",
    amarPutusan: "Mengabulkan permohonan kasasi; Membatalkan putusan Pengadilan Tinggi.",
    ringkasanSingkat: "Kasasi sengketa tanah dikabulkan; putusan banding dibatalkan.",
    fullText:
      "P U T U S A N\nNomor 902 K/Pdt/2019\nMENGADILI\nMengabulkan permohonan kasasi dari Pemohon Kasasi; Membatalkan putusan Pengadilan Tinggi Denpasar; Mengadili sendiri.",
    pdfUrl: null,
  }),
  demo({
    sourceUrl: `${SRC}/demo-66pidsusanak2022`,
    nomorPutusan: "66/Pid.Sus-Anak/2022/PN Bdg",
    tingkatProses: "Pertama",
    klasifikasi: "Pidana Khusus Anak",
    kataKunci: ["anak", "diversi", "perlindungan anak"],
    tahun: 2022,
    tanggalPutusan: "2022-09-05",
    lembagaPeradilan: "Pengadilan Negeri Bandung",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "PN Bandung",
    provinsi: "Jawa Barat",
    hakim: ["Sri Wahyuni, S.H., M.H."],
    pihak: ["Jaksa Penuntut Umum", "Anak (inisial dilindungi)"],
    amarPutusan: "Menjatuhkan tindakan berupa pembinaan di dalam lembaga.",
    ringkasanSingkat: "Perkara pidana anak; dijatuhkan tindakan pembinaan dalam lembaga.",
    fullText:
      "P U T U S A N\nNomor 66/Pid.Sus-Anak/2022/PN Bdg\nMENGADILI\nMenjatuhkan tindakan kepada Anak berupa pembinaan di dalam lembaga selama 6 (enam) bulan.",
    pdfUrl: null,
  }),
  demo({
    sourceUrl: `${SRC}/demo-21pdtsusphi2023`,
    nomorPutusan: "21/Pdt.Sus-PHI/2023/PN Smg",
    tingkatProses: "Pertama",
    klasifikasi: "Perdata Khusus",
    kataKunci: ["PHK", "hubungan industrial", "pesangon"],
    tahun: 2023,
    tanggalPutusan: "2023-03-14",
    lembagaPeradilan: "Pengadilan Hubungan Industrial Semarang",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "PHI Semarang",
    provinsi: "Jawa Tengah",
    hakim: ["Agus Salim, S.H.", "Retno Wulandari, S.H., M.H."],
    penggugat: "Serikat Pekerja Mandiri",
    tergugat: "PT Tekstil Jaya",
    pihak: ["Serikat Pekerja Mandiri", "PT Tekstil Jaya"],
    amarPutusan:
      "Mengabulkan gugatan untuk sebagian; Menghukum Tergugat membayar uang pesangon dan penghargaan masa kerja.",
    ringkasanSingkat: "Sengketa PHK; Tergugat dihukum membayar pesangon.",
    fullText:
      "P U T U S A N\nNomor 21/Pdt.Sus-PHI/2023/PN Smg\nMENGADILI\nMengabulkan gugatan Penggugat untuk sebagian; Menghukum Tergugat membayar uang pesangon, uang penghargaan masa kerja, dan uang penggantian hak.",
    pdfUrl: `${SRC}/demo-21pdtsusphi2023/pdf`,
  }),
  demo({
    sourceUrl: `${SRC}/demo-4567kpid2018`,
    nomorPutusan: "4567 K/Pid/2018",
    tingkatProses: "Kasasi",
    klasifikasi: "Pidana Umum",
    kataKunci: ["pencurian", "pemberatan"],
    tahun: 2018,
    tanggalPutusan: "2018-12-03",
    lembagaPeradilan: "Mahkamah Agung",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "Mahkamah Agung",
    provinsi: "DKI Jakarta",
    hakim: ["Andi Samsan Nganro, S.H., M.H."],
    terdakwa: "RH bin MT",
    pihak: ["Jaksa Penuntut Umum", "RH bin MT"],
    amarPutusan: "Menolak permohonan kasasi dari Terdakwa.",
    ringkasanSingkat: "Kasasi terdakwa pencurian dengan pemberatan ditolak.",
    fullText:
      "P U T U S A N\nNomor 4567 K/Pid/2018\nMENGADILI\nMenolak permohonan kasasi dari Pemohon Kasasi/Terdakwa RH bin MT.",
    pdfUrl: null,
  }),
  demo({
    sourceUrl: `${SRC}/demo-9bpa2023`,
    nomorPutusan: "9/Pdt.G/2023/PA Mks",
    tingkatProses: "Pertama",
    klasifikasi: "Agama",
    kataKunci: ["cerai gugat", "perkawinan"],
    tahun: 2023,
    tanggalPutusan: "2023-05-22",
    lembagaPeradilan: "Pengadilan Agama Makassar",
    jenisLembagaPeradilan: "Agama",
    pengadilan: "PA Makassar",
    provinsi: "Sulawesi Selatan",
    hakim: ["Drs. H. Abdul Rahman, M.H."],
    penggugat: "Penggugat (inisial dilindungi)",
    tergugat: "Tergugat (inisial dilindungi)",
    pihak: ["Penggugat", "Tergugat"],
    amarPutusan: "Mengabulkan gugatan Penggugat; Menjatuhkan talak satu ba'in sughra.",
    ringkasanSingkat: "Cerai gugat dikabulkan.",
    fullText:
      "P U T U S A N\nNomor 9/Pdt.G/2023/PA Mks\nMENGADILI\nMengabulkan gugatan Penggugat; Menjatuhkan talak satu ba'in sughra Tergugat terhadap Penggugat.",
    pdfUrl: `${SRC}/demo-9bpa2023/pdf`,
  }),
  demo({
    sourceUrl: `${SRC}/demo-1290kpidsus2020`,
    nomorPutusan: "1290 K/Pid.Sus/2020",
    tingkatProses: "Kasasi",
    klasifikasi: "Pidana Khusus",
    kataKunci: ["narkotika", "pasal 114 UU Narkotika"],
    tahun: 2020,
    tanggalPutusan: "2020-10-14",
    lembagaPeradilan: "Mahkamah Agung",
    jenisLembagaPeradilan: "Umum",
    pengadilan: "Mahkamah Agung",
    provinsi: "DKI Jakarta",
    hakim: ["Desnayeti M, S.H., M.H.", "Yohanes Priyana, S.H., M.H."],
    terdakwa: "FH bin AK",
    pihak: ["Jaksa Penuntut Umum", "FH bin AK"],
    amarPutusan: "Menolak permohonan kasasi; Menguatkan putusan judex facti.",
    ringkasanSingkat: "Kasasi perkara narkotika ditolak.",
    fullText:
      "P U T U S A N\nNomor 1290 K/Pid.Sus/2020\nMENGADILI\nMenolak permohonan kasasi dari Pemohon Kasasi/Terdakwa FH bin AK.",
    pdfUrl: null,
  }),
  demo({
    sourceUrl: `${SRC}/demo-55pthun2019`,
    nomorPutusan: "55/B/2019/PT.TUN.Jkt",
    tingkatProses: "Banding",
    klasifikasi: "Tata Usaha Negara",
    kataKunci: ["banding", "pertanahan"],
    tahun: 2019,
    tanggalPutusan: "2019-04-30",
    lembagaPeradilan: "Pengadilan Tinggi Tata Usaha Negara Jakarta",
    jenisLembagaPeradilan: "Tata Usaha Negara",
    pengadilan: "PT TUN Jakarta",
    provinsi: "DKI Jakarta",
    hakim: ["Irfan Fachruddin, S.H., M.H."],
    pihak: ["PT Properti Utama", "Badan Pertanahan Nasional"],
    penggugat: "PT Properti Utama",
    tergugat: "Badan Pertanahan Nasional",
    amarPutusan: "Menguatkan putusan Pengadilan Tata Usaha Negara tingkat pertama.",
    ringkasanSingkat: "Putusan banding menguatkan putusan tingkat pertama.",
    fullText:
      "P U T U S A N\nNomor 55/B/2019/PT.TUN.Jkt\nMENGADILI\nMenerima permohonan banding; Menguatkan putusan Pengadilan Tata Usaha Negara Jakarta.",
    pdfUrl: `${SRC}/demo-55pthun2019/pdf`,
  }),
];
